### ISSUE TITLE
cmake sssl build trouble

### ISSUE THREAD

**Issue by prlw1** [Openwsman/openwsman#87] opened 2016-02-29 11:11 UTC
Given the note in autoconfiscate.sh:
```
echo "*** Autoconf/automake is deprecated for Openwsman"
echo "*** and might not fully work."
echo "*** Use cmake instead !"
```
I just tried cmake on head, and see
```
-- Version 2.6.2
-- Package Version "2.6"
-- Plugin API Version "2.2"
CMake Error at CMakeLists.txt:37 (STRING):
  string sub-command REPLACE requires at least four arguments.

# Package architecture
IF ( NOT DEFINED PACKAGE_ARCHITECTURE )
 EXECUTE_PROCESS(COMMAND "/bin/uname" "-m" OUTPUT_VARIABLE UNAME_M)
 # strip trailing newline
 STRING(REPLACE "\n" "" PACKAGE_ARCHITECTURE ${UNAME_M})
ENDIF ( NOT DEFINED PACKAGE_ARCHITECTURE )
```
looks as though it is using the variable PACKAGE_ARCHITECTURE precisely in the conditional block in which it is not defined.

Puzzled, but unrelated:
```
-- Found OpenSSL: /usr/lib/libssl.so;/lib/libcrypto.so (found version "1.0.1r") 
...
-- SSL_LIB is at ><
```

**Comment by kkaempf** [comment] 2016-02-29 13:56
Thanks. I didn't see this problem before since my standard way of calling cmake is
```
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=TRUE -DCMAKE_SKIP_RPATH=1 -DPACKAGE_ARCHITECTURE=`uname -m` -DBUILD_TESTS=YES $@ ..
```

**Comment by kkaempf** [comment] 2016-02-29 13:57
Hmm, even if I leave `-DPACKAGE_ARCHITECTURE=` out
```
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=TRUE -DCMAKE_SKIP_RPATH=1 -DBUILD_TESTS=YES $@ ..
```
the above error is *not* triggered.

How can I reproduce your issue ?

**Comment by kkaempf** [comment] 2016-02-29 14:01
The [cmake documentation](https://cmake.org/cmake/help/v3.0/command/string.html) reads
```
string(REPLACE <match_string>
       <replace_string> <output variable>
       <input> [<input>...])
```
So in
```
STRING(REPLACE "\n" "" PACKAGE_ARCHITECTURE ${UNAME_M})
```
`PACKAGE_ARCHITECTURE` is the output variable.

**Comment by kkaempf** [comment] 2016-02-29 14:02
What's the output of `/bin/uname -m` on your system ?

**Comment by kkaempf** [comment] 2016-02-29 14:04
About SSL:

What is the output of `ls -l /usr/lib/libssl.so` ?

**Comment by prlw1** [comment] 2016-02-29 15:46
Ah:

$ which uname
/usr/bin/uname

$ ls -l /usr/lib/libssl.so
lrwxr-xr-x  1 root  wheel  14 Feb 24 09:36 /usr/lib/libssl.so -> libssl.so.10.5

**Comment by kkaempf** [comment] 2016-02-29 21:27
What's the output of `/bin/uname -m` on your system ?

**Comment by kkaempf** [comment] 2016-02-29 21:29
What is the output of `/usr/bin/readlink /usr/lib/libssl.so` on your system ?

**Comment by prlw1** [comment] 2016-03-01 07:45
/bin/uname doesn't exist on my system
$ /usr/bin/uname -m
amd64
$ /usr/bin/readlink /usr/lib/libssl.so
libssl.so.10.5

**Comment by prlw1** [comment] 2016-03-30 14:46
diff --git a/CMakeLists.txt b/CMakeLists.txt
index bb616a6..d22734d 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -32,7 +32,7 @@ SET(OPENWSMAN_PLUGIN_API_VERSION \"${OPENWSMAN_PLUGIN_API_MAJOR}.${OPENWSMAN_PLU
 
 # Package architecture
 IF ( NOT DEFINED PACKAGE_ARCHITECTURE )
- EXECUTE_PROCESS(COMMAND "/bin/uname" "-m" OUTPUT_VARIABLE UNAME_M)
+ EXECUTE_PROCESS(COMMAND "uname" "-m" OUTPUT_VARIABLE UNAME_M)
  # strip trailing newline
  STRING(REPLACE "\n" "" PACKAGE_ARCHITECTURE ${UNAME_M})
 ENDIF ( NOT DEFINED PACKAGE_ARCHITECTURE )

i.e., leave it up to $PATH to find uname, gets us further.


There seems to be the following far-sighted comment in CMakeLists.txt:

#
# The wsman_config file checks functions existance via "#if",
# requiring a 0/1 argument
# CHECK_FUNCTION_EXISTS however, returns ""/"1" resulting in
# an empty argument to "#if" in the 'false' case
# The code below ensures that "HAVE_xxx" is set to "0" or "1"
#

yet just before it we have:

CHECK_FUNCTION_EXISTS( "alloca" HAVE_ALLOCA )
IF (NOT HAVE_ALLOCA)
  SET(HAVE_ALLOCA 0)
  SET(C_ALLOCA 0)
  CHECK_INCLUDE_FILE( "alloca.h" HAVE_ALLOCA_H )
ENDIF (NOT HAVE_ALLOCA)

which somehow leads to the following in wsman_config.h:

/* Define to 1 if you have <alloca.h> and it should be used (not on Ultrix).
   */
#if 
#define HAVE_ALLOCA_H 1
#endif

(Note the lack of argument to #if) FWIW I don't have alloca.h => that should be #if 0.

**Comment by apjanke** [comment] 2016-05-01 14:42
I see the same problem on OS X 10.9. `uname` there is `/usr/bin/uname` as well. I was able to fix it by having it just call `uname` instead of the fully-qualified `/bin/uname`.

**Comment by kkaempf** [comment] 2016-05-11 07:51
The `alloca` problem should be fixed with 2f6b64b.

**Comment by kkaempf** [comment] 2016-05-11 07:52
The `SSL_LIB` problem should be fixable (well, workarounded) by passing `-DLIB=lib` to CMake.

**Comment by kkaempf** [comment] 2016-05-11 07:53
@prlw1 what's your operating system ?

**Comment by prlw1** [comment] 2016-05-11 08:55
On Wed, May 11, 2016 at 12:53:14AM -0700, Klaus Kmpf wrote:
> @prlw1 what's your operating system ?

NetBSD

**Comment by kkaempf** [comment] 2016-06-21 07:13
I believe most of the mentioned issues are fixed, thus closing this issue. If problems remain, please open a new issue.

**Closed by kkaempf** 2016-06-21 07:13 UTC
